// SOURCE: ECG OFFICIAL LOAD MANAGEMENT SCHEDULE - APRIL 25 TO MAY 1, 2026

export const SCHEDULE_DATES = [
  { date: "2026-04-25", day: "Saturday",  slots: [{ group:"A", start:"06:00", end:"12:00" }, { group:"B", start:"12:00", end:"18:00" }, { group:"C", start:"18:00", end:"00:00" }, { group:"A", start:"00:00", end:"06:00" }] },
  { date: "2026-04-26", day: "Sunday",    slots: [{ group:"B", start:"06:00", end:"12:00" }, { group:"C", start:"12:00", end:"18:00" }, { group:"A", start:"18:00", end:"00:00" }, { group:"B", start:"00:00", end:"06:00" }] },
  { date: "2026-04-27", day: "Monday",    slots: [{ group:"C", start:"06:00", end:"12:00" }, { group:"A", start:"12:00", end:"18:00" }, { group:"B", start:"18:00", end:"00:00" }, { group:"C", start:"00:00", end:"06:00" }] },
  { date: "2026-04-28", day: "Tuesday",   slots: [{ group:"A", start:"06:00", end:"12:00" }, { group:"B", start:"12:00", end:"18:00" }, { group:"C", start:"18:00", end:"00:00" }, { group:"A", start:"00:00", end:"06:00" }] },
  { date: "2026-04-29", day: "Wednesday", slots: [{ group:"B", start:"06:00", end:"12:00" }, { group:"C", start:"12:00", end:"18:00" }, { group:"A", start:"18:00", end:"00:00" }, { group:"B", start:"00:00", end:"06:00" }] },
  { date: "2026-04-30", day: "Thursday",  slots: [{ group:"C", start:"06:00", end:"12:00" }, { group:"A", start:"12:00", end:"18:00" }, { group:"B", start:"18:00", end:"00:00" }, { group:"C", start:"00:00", end:"06:00" }] },
  { date: "2026-05-01", day: "Friday",    slots: [{ group:"A", start:"06:00", end:"12:00" }, { group:"B", start:"12:00", end:"18:00" }, { group:"C", start:"18:00", end:"00:00" }, { group:"A", start:"00:00", end:"06:00" }] },
];

export const REGIONS_DATA = [
  {
    "id": "accra",
    "name": "Accra",
    "groups": {
      "A": [
        "South Odorkor",
        "St. Anthony",
        "Lawyer Kom",
        "Baah Yard",
        "Odorgonno",
        "Awoshie Massalatsi",
        "Victory Bible Church",
        "Been-To",
        "Parts of Trasacco Estates",
        "Parts of Zoomlion",
        "Obinim",
        "Parts of Airport Residential Area",
        "Opeibia",
        "Coffee Farmers Association",
        "Dr. Atekpe",
        "Adabraka Free Town",
        "Catholic Book Centre",
        "Government Boys",
        "GNTC Bottling",
        "Nayak",
        "Dome New Market",
        "Agingo",
        "Taifa",
        "Nkatie Burger",
        "Mr. Adjei",
        "Demod",
        "Hotel Adodo",
        "CMB Flats",
        "Olebu",
        "Canada City",
        "New Ayawaso",
        "Amamole",
        "Ayigbe Town",
        "Zoti",
        "Parts of Lartebiokorshie",
        "Alogboshie",
        "Neoplan",
        "Best Point",
        "West Africa Décor",
        "Kaneshie Flats",
        "St. Theresa",
        "Cocoa Clinic",
        "Accra Sound",
        "Kaneshie Sports Complex",
        "Parts of Kokomlemle",
        "Mallam Atta Market",
        "Parts of Accra New Town",
        "Timber Market",
        "Parts of Asylum Down",
        "Gye Nyame Hotel",
        "NPP Office",
        "Agoro TV",
        "Makola",
        "Angelina House",
        "Tudu/Aflao Station",
        "UMB Bank",
        "Liberty House",
        "Parts of Katamanto",
        "Swam Mill",
        "PZ",
        "Wato",
        "Charles Lane",
        "James Town Police Station",
        "Akotoku Academy",
        "Pig Farm",
        "Kotobabi Police Station",
        "Club 1000",
        "Expo 67",
        "Abavana",
        "Parts of Kotobabi Polyclinic",
        "Asofa",
        "Amen Amen",
        "Seven Days",
        "Atta Mills",
        "Parts of Ofankor",
        "Amelia",
        "Pokuase Interchange",
        "Agya Herbal",
        "Ofankor Railway Bridge",
        "Congo Junction",
        "Burma Camp Goil Filling Station",
        "Parts of Palm Wine Junction",
        "Rawlings Circle",
        "Madina Market",
        "Madina Mosque",
        "Parts of Maye Hot",
        "Atomic Junction",
        "North Legon",
        "Ghana Hostels",
        "Libya Quarters",
        "Washington",
        "Parts of Nsawam Township",
        "Oparekrom",
        "Adoagyiri",
        "Abotsi Hanya",
        "Awula Wulu",
        "Ayalolo",
        "Aboma",
        "Parts of Greda Estates",
        "Pentecost University",
        "Israel",
        "Parts of Alhaji",
        "Parts of Sowutuom",
        "Antieku",
        "Baron",
        "Amrahia",
        "Danfa",
        "Otinibi",
        "Parts of Malejor",
        "Amanfro",
        "Zenith College",
        "Exzorpa",
        "Tseaddo",
        "New England",
        "Chain Homes",
        "Madina Estate and its environs",
        "Legon Hills",
        "Santoe",
        "eshie Nungua Estaes",
        "Parts of Adogonno",
        "1st Junction",
        "Telecom",
        "Wele",
        "Akoto Bu",
        "Heritage Tower",
        "Ecobank HQ",
        "Ridge Tower",
        "College of Physicians & Surgeons",
        "Pegasus",
        "World Bank",
        "Ringway Estates",
        "Parts of NIC",
        "Joma Township",
        "Ablekuma Agape",
        "Suncity",
        "Adwensa Publication",
        "Adenta Estates",
        "Commando",
        "New Legon",
        "Lotto Kiosk",
        "Paa Willy Junction",
        "Parts of Mataheko",
        "Adeiso",
        "Coaltar",
        "Otoase",
        "Krabokese",
        "Marfokrom",
        "Fankyenekor",
        "Kofi Quaye",
        "Dorkotwoa",
        "Nkran",
        "Forest Hotel",
        "Agorwu",
        "Sasaabi",
        "Kpone Seduase",
        "Valley View University",
        "Oyibi",
        "Apollonia",
        "Pantang Hospital",
        "Nyamekrom",
        "Parts of Abokobi",
        "Oxford Street",
        "Kalamazoo",
        "Bosomtwi Hotel",
        "Beijing Clinic",
        "Ablekuma Tigo pole",
        "Borkorborkor",
        "Manhia",
        "Afoaman",
        "Afiaman",
        "CP",
        "Maame Nkran",
        "Part of Joma",
        "Mayera",
        "Denu",
        "part of Kuntunse",
        "Amasaman",
        "Fise",
        "part of Toman",
        "Part of Okponglo",
        "Erata Hotel",
        "Part of East Legon",
        "Bawaleshie",
        "Madina",
        "PRESEC",
        "UPSA",
        "Pentecost Hospital",
        "Social Welfare",
        "TV Africa",
        "Danafco",
        "Fan Milk Annex",
        "SSNIT Archives",
        "Part of Kwashieman",
        "Nii Boye Town",
        "Abrantie Spot",
        "Lapaz",
        "King of Kings",
        "Parts of Odorkor Alabama",
        "Darkuman Mosque",
        "Darkuman Quarters",
        "Asantewaa Hotel",
        "Raaco",
        "Kpehe Catholic Church",
        "Police Depot",
        "Armoring",
        "Police Detective Academy",
        "GTUC Campus",
        "Parts of Tesano",
        "John Teye SHS",
        "Ayigbe Park",
        "Kwabenya Adom",
        "Azonto",
        "Police Quarters",
        "Capital Hill",
        "Parts of Asofa",
        "Hallem",
        "Joe Joe",
        "Emmanuel Eye Clinic",
        "Legon",
        "Mensvic Hotel",
        "Ecole Francaise",
        "Kings Cottage",
        "Maxixis Tires",
        "Western World Trading",
        "East Cantonment",
        "Max Mart",
        "Butler Lines",
        "Opeibea",
        "Japan Motors",
        "Lakeside Community 1 & 8",
        "Saphier Plastics",
        "Mallam Junction",
        "Sotrec",
        "Jayee University",
        "Menskrom",
        "Sakuman",
        "Mallam Market",
        "Blue Lagoon",
        "Parts of Dansoman SSNIT Flats",
        "Parts of Sukura",
        "Parts of Appiah Danquah",
        "Zamrama Line",
        "Adjirigannor",
        "Islamic University",
        "NTHC Estates",
        "Parts of America House",
        "National Archives",
        "Parts of Adabraka",
        "Ministry of Information",
        "Teachers Hall",
        "Adabraka Methodist",
        "Ashongaman Estates",
        "Obaahemaa",
        "Aggies Spot",
        "Parts of Atomic Commission",
        "Dome Pillar",
        "Atomic Guest House",
        "Konka",
        "Asafo Adjei",
        "Sawmill",
        "Independence Square",
        "Osu Anglican",
        "Photo Club",
        "Tiokor",
        "Parts of Osu Oxford Street",
        "La T-Junction",
        "La Palm Royal Beach Hotel",
        "La Beach Hotel",
        "Regimanuel Grey HQ",
        "Agyeman",
        "La Cemetery",
        "Palm Wine Junction",
        "Kojo Sardine",
        "Nativity",
        "Fan Milk",
        "Agbeve Top",
        "Ablekuma Abease",
        "Abibiman School",
        "Atico",
        "Parts of North Kaneshie",
        "Parts of New Fadama",
        "Chief Iman",
        "St Ann's School",
        "Daily Foods",
        "Winners Chapel",
        "Dark Mark",
        "City Appliance",
        "Parts of Abossey Okai",
        "Sabon Zongo",
        "Okponglo Booster Station",
        "North Dzorwulu",
        "Accra Shopping Mall",
        "Woolworth",
        "Polo Court",
        "Aviation House",
        "Villagio",
        "Africa Regency Hotel",
        "Airport West Hotel",
        "Mataheko Police Barracks",
        "Bella Hotel",
        "Gloriland Hotel",
        "Arts Commercial Centre",
        "KNUST Campus",
        "Abuom",
        "Bethel",
        "Comet Estates",
        "Bank of Ghana Quarters",
        "Katapor",
        "Second Chance",
        "Adusa Quarters",
        "Dedeman",
        "Pito House",
        "Fulgrip",
        "NADMO",
        "PH Hotel",
        "Kofi Capito",
        "Otieshie",
        "Ogbojo CSIR and its environs",
        "Abofu",
        "New Achimota Station",
        "Dar Es Salam",
        "Composite Site",
        "Sea Lady",
        "Manna Mission Hospital",
        "Camp 2",
        "Rasta",
        "Teshie Demo",
        "Tebibiano",
        "Parts of Nmai Djorn",
        "Parts of Legon Hills"
      ],
      "B": [
        "Abossey Okai",
        "Zongo Junction",
        "Kaneshie Orange Market",
        "Parts of Lartebiokorshie",
        "IBE",
        "Parts of Mamprobi",
        "Akoshie Junction",
        "Kamara",
        "Tot-To Teen School",
        "SDA Junction",
        "La Nkwantana",
        "Akatsi Abor",
        "Power Line",
        "Special Ice",
        "Ayi Mensah",
        "Ghana Flag",
        "Special Drink",
        "Oyarifa",
        "Obeyeyie",
        "Akramaman",
        "Yahoman",
        "Ayikai Doblo",
        "Pobiman",
        "Treba",
        "Parts of Greda Estates",
        "Tsui Bleoo",
        "Agblezaa",
        "Tebibiano",
        "Yomo Specs",
        "Akuaba Estates",
        "Brekusu",
        "Agyemanti",
        "Comet Estates",
        "Atinka Media",
        "Aburi Sec. Tech",
        "Ahwerease New Site",
        "Ahwerease Teachers Bungalow",
        "Lord Care cold store",
        "Alioma",
        "Kingsway",
        "Japan Embassy",
        "Korea Embassy",
        "Miklin Apartments",
        "Food Research",
        "Kukuhill",
        "Morning Star",
        "Trinity Seminary",
        "Mempeasem",
        "UG Business School",
        "Atraco",
        "UPSA Hostel",
        "Nsawam Prisons",
        "Parts of Doblo",
        "Hebron",
        "Agya Appiah",
        "Blue Skies",
        "Ashale Botwe Old Town",
        "Little Roses",
        "Parts of Nanakrom",
        "Pentecost Down",
        "Okpoi Gonno",
        "Parts of Adjorman",
        "Marvel House",
        "Adjoa Wangara",
        "Knight Court",
        "Embassy Hotel",
        "Dubois Center",
        "American Embassy",
        "Arabian Embassy",
        "France Embassy",
        "Ghana International School",
        "Mamobi",
        "Accra Girls",
        "Kotobabi",
        "Township",
        "Ashieye",
        "Aseidu Nketia",
        "Gravel Pit",
        "Regimanuel Estates Spintex Rd",
        "Parts of Odorkor",
        "Parts of Odorkor Official Town",
        "Junction",
        "Great Garden",
        "Mangoasie",
        "Parts of Kwashieman",
        "Parts of Official Town",
        "Parts of Santamaria",
        "Kwashiebu",
        "Race Course",
        "Tabora",
        "Parts of Alhaji",
        "Bantsi asi",
        "F. Malawi",
        "Goil HQ",
        "Central Police Station (MTTD)",
        "AirtelTigo HQ",
        "Musuku",
        "Oscar",
        "Point 1",
        "Balloon Gate",
        "Stages",
        "Haatso Yam Market",
        "Emefa Jewelleries",
        "Legon Botanical Gardens",
        "Peduase Lodge",
        "Kitase",
        "Ahwerease",
        "Aburi SHS",
        "Ayim",
        "Ashongman Village",
        "Pure Water",
        "Ashongman City",
        "Gbawe Bulemi",
        "Gonse",
        "Djaman",
        "Oblogo",
        "Parts of Weija Dam Site",
        "Ghana Standard Authority",
        "Obama Hotel",
        "Parts of Okonglo",
        "GS Plaza",
        "Gecko",
        "Golf House",
        "National Identification Authoruty",
        "CSIR",
        "Nitra",
        "EPPL",
        "Terry Cot",
        "Century Industries",
        "Parks & Shops",
        "Kokompe",
        "Parts of Darkuman",
        "Agbogbloshie",
        "Abossey Okai Central Mosque",
        "Sikkens",
        "Pure Fire",
        "Christian Village",
        "Golf Park",
        "Sober",
        "Kisseiman",
        "Parts of Westland",
        "Haatso Trotro Station",
        "Brainy Brain School",
        "Hydrofam Estates",
        "Frempongmaa Estates",
        "Parts of Okpoi Gonno",
        "Association International School",
        "Parts of Airport Residential Area",
        "Newmont Ghana",
        "Falcon",
        "Gold House",
        "WAEC",
        "Cedar Court",
        "Capital Place",
        "Tang Palace Hotel",
        "Mplaza Hotel",
        "Bostal",
        "Roman Ridge Shopping Arcade",
        "DevTraco Estates",
        "Twumasiwaa Hospital",
        "Djen Ayor",
        "Fa Asem Kyea",
        "Parts of Ogbojo",
        "Local Government",
        "Twuamasiwaa Rounabout",
        "ARS",
        "Appiah Danquah",
        "Flamingo",
        "Radio Gold",
        "Parts of Dome",
        "Ikam",
        "Asene Household",
        "Kumbaya Hotel",
        "Francisca Tower",
        "Vodafone",
        "Multi TV",
        "Parts of Kokomlemle",
        "Horizon Finance Levsing Co.",
        "GWC La",
        "Akrowa House",
        "La- T junction",
        "Labone",
        "La Wireless Station",
        "Alisa Hotel",
        "Nmai Djorn",
        "School Junction",
        "Akweteman",
        "Bambolino",
        "Shaaba",
        "Parts of Abeka Free Pipe",
        "Mama's Inn",
        "Dansoman Keep Fit",
        "SSNIT Flats",
        "King Solomon",
        "Otorjor",
        "Movenpick",
        "Accra City Hotel",
        "Supreme Court",
        "Fast Track Court",
        "Opera Square",
        "Ghana Post",
        "M&G Pharmaceuticals",
        "Oceanic Resort",
        "New Bortianor",
        "Osiadan",
        "Dunkona",
        "Red Top",
        "New Aplaku",
        "Kings University",
        "Burger Town",
        "Parts of Abokobi",
        "Teiman Township",
        "Okponkpo",
        "Abloradjei",
        "part of Akporman",
        "Top Herbal",
        "Bohye",
        "Wisconsin University",
        "Busy Internet",
        "GRA",
        "Niagara",
        "part os Asylum Down",
        "Providence Tower",
        "Iran Clinic",
        "Nkrumah Circle",
        "GCB Tower",
        "Ayalolo",
        "Diamond House",
        "Registrar General",
        "Ghana News Agency",
        "Fulani",
        "Tuba",
        "Langba",
        "Kokrobitey",
        "Achimota Market",
        "Naa Densua",
        "Achimota Halt Tower",
        "Banana Inn",
        "Mabruk Park",
        "part of Zabrama Line",
        "Osofo Dadzie",
        "Mascot",
        "Mamponsee",
        "Village Gate",
        "Pantang Junction",
        "Focos Hospital",
        "Shalom Estates",
        "Kottam Estates",
        "Swiss Embassy",
        "Diamond Ridge",
        "AU Estates",
        "North Ridge Hotel",
        "Accra High School",
        "NHIS HQ",
        "MTN HQ",
        "Merchant Bank",
        "Alisa Village",
        "Latter Days Saints",
        "Parts of Nyamekye",
        "MAB Hospital",
        "Kwashie-Bu",
        "Parts of Anyaa",
        "Nsumfa",
        "NIC Top",
        "Parts of Sowutuom",
        "Seminary",
        "Omanjor",
        "VRA Flats",
        "Mambo Spot",
        "Agape Junction",
        "B-Opoku",
        "Sahara",
        "Dr. Beechem",
        "Control Market",
        "Kit-Kat",
        "Parts of Dansoman",
        "Mars Junction",
        "Russia",
        "Sukura Market",
        "Lonso Park",
        "Epo",
        "Trust Hospital",
        "Osu Entertainement",
        "Parts of Osu Oxford Street",
        "Koala",
        "Citien Kofi",
        "Coffee Shop",
        "Labone GNTC",
        "Cantonment",
        "BOG Hospital",
        "NAFTI",
        "Mechanization",
        "Kwabina Adjei Homes",
        "Ashiye",
        "TseAddo"
      ],
      "C": [
        "Asylum Down",
        "Parts",
        "Geological Survey",
        "Parts of West Ridge",
        "Best Cuisine",
        "Atomic Commission",
        "Haatso Ecomog",
        "Parts of Dome Pillar",
        "K Boat",
        "Zita Lane",
        "Paradise Lodge",
        "Mallam Abease",
        "Parts of McCarthy Hill",
        "Gbawe Zero",
        "Top Base",
        "Parts of Gonse",
        "Salaga Market",
        "Parts of James Town",
        "Cadbury",
        "Interprise Insurance",
        "Baiden Powers",
        "La Beach Road",
        "Family Health Hospital",
        "Teshie Maami",
        "Speedy",
        "Flower Pot",
        "Palace Mall",
        "Oak Plaza Hotel",
        "Sonitra",
        "Parts of Airport Hills",
        "Bubiashie Cable & Wireless",
        "Ayigbe Town",
        "Morning Star School",
        "Labone",
        "Achimota School",
        "Achimota Police Station",
        "McBright Tower",
        "Choice",
        "Shikpontele",
        "Toman",
        "Parts of Pokuase Township",
        "Parts of Pobiman",
        "Agya Appiah",
        "Ecoblock",
        "SEL Filling Station",
        "Fountain Gate",
        "Parts of John Teye",
        "Franko Estates",
        "Chorkor",
        "Agege Lorry Park",
        "Chemuanaa",
        "Sempe",
        "Dan Wright",
        "Korle Gonno",
        "St Mary SHS",
        "Mile 7",
        "Maple Leaf",
        "Parts of New Achimota",
        "Petroleum",
        "Kinsby",
        "Parts of Nii Boi Town",
        "New Achimota",
        "Chantan",
        "Shiabu",
        "Dansoman Beach Road",
        "Gbegbeyisee",
        "Tesano",
        "Parts of Alajo",
        "Charleston Hotel",
        "Santana Market",
        "De-Georgia Motors",
        "Letap Jewelleries",
        "Beyeeman",
        "Princess Coldstore",
        "Honda Place",
        "Parts of South Industrial Area",
        "Children Hospital",
        "Timber Market",
        "Palladium",
        "Katamanto Market",
        "Ebony",
        "Kotobabi Down",
        "Abavana Down",
        "Agbadzenaa",
        "Nkansah Djan",
        "Ayidiki",
        "Parts of Dorwulu",
        "Abelemkpe",
        "Pere Dome",
        "Marwako",
        "Special School",
        "Nsawam Market",
        "Nsawam Hospital",
        "Nsumia",
        "Mikado",
        "Akramaman",
        "Sakyikrom",
        "Anoff",
        "Piabor",
        "Prisons",
        "Police Hospital",
        "Forestry Commission",
        "Teiman Township",
        "Burgar Town",
        "Bawaleshie and its enirons",
        "Madina Social Welfare",
        "Maye Hot and uts environs",
        "Vineyard",
        "3rd Gate",
        "Aviation",
        "Peace Be",
        "Parts of Ashale Botwe",
        "Parts of Maye Hot",
        "Frafraha",
        "Rowi Junction",
        "Mother Love",
        "Ampomaa Estates",
        "Dobro",
        "Sapeiman",
        "Amasaman",
        "Opah",
        "Ablorman",
        "Tenor",
        "Africola",
        "Hebron",
        "Satelite",
        "Fair Heaven",
        "Community 5",
        "Rojo Roso",
        "Lake Community 8",
        "Sraha",
        "St. Peters",
        "Nsakina New Town",
        "Peace Village",
        "Dromonaa",
        "Obeng City",
        "Oshuman",
        "Ga-Odumase",
        "Nyamekye",
        "Part of Fadama",
        "Eno Mirekua",
        "KPOGAS",
        "Part of Lorgotsu-shie",
        "part Agyeman",
        "La Presby",
        "Part of Ofankor",
        "Muus",
        "Bulk Press",
        "Part of Tantra Hill",
        "Spot M",
        "SSNIT Flat Tantra Hill",
        "St. John",
        "Akokor Photo",
        "KFC",
        "SDA Southern HQ",
        "BOG Flats at Mataheko",
        "Sakoa Press",
        "Part of Flamingo",
        "Awoshie Baah yard",
        "Mangoase",
        "A-Lang",
        "New Gbawe",
        "Odorgonnor",
        "Part of MacCarthy Hill",
        "Weija Junction",
        "Tetegu",
        "Part of Sampa Valley",
        "Dodowa Hospital",
        "Ayikuma",
        "Doryimu",
        "Kordiabe",
        "Agormeda",
        "Gegedekum",
        "Jarpanya",
        "Apese",
        "SCC",
        "Parts of Weja",
        "Gicel",
        "Mandela",
        "GBC Quarters",
        "Mile 11",
        "Broadcasting Last Stop",
        "Parts of Bortianor",
        "American Flag",
        "Kasapa",
        "Dorwulu",
        "Bayere Junction",
        "Sid Studio",
        "Reservoir",
        "Absolute Furnitures",
        "Petroleum Commission",
        "Paloma",
        "Nima",
        "Frankies",
        "Nima Gutter",
        "Nima Rounabout",
        "Nima Market",
        "Quality Insurance",
        "Mogya Biedon",
        "Glefe",
        "Wiaborman",
        "Ebenezer SHS",
        "Atomic Hotel",
        "Dansoman Last Stop",
        "Village Gate",
        "Mamponsee",
        "Karikari Brobbey Park",
        "Awoshie Water Works",
        "Sakaman Junction",
        "Mallam Market",
        "Parts of Gbawe",
        "Janus Ltd",
        "Gyamfi Apartment",
        "Lecacy Closet",
        "Kofi Baako",
        "National Security Communication bureau",
        "Zanzibar",
        "New TseAddo",
        "New England",
        "Tebibianor road",
        "Kordjor area",
        "Tebibiano Masalatsi area",
        "Parts of camp 2 taxi rank last stop",
        "Boshye",
        "Academic City University",
        "Ajirigannor",
        "Coffee Shop",
        "Abeka Market",
        "Asare Original Pay All",
        "Parts of New Fadama",
        "Adom Clinic",
        "La Wireless",
        "Teiman",
        "Tse Addo",
        "Rosa Rosa",
        "Kotoku",
        "Medie",
        "Blue Skies",
        "East Legon Hills",
        "Soja Line",
        "Lake Side Comm. 8",
        "Katamanso",
        "Paradise Estate",
        "Regimanuel",
        "Adom Gate",
        "Ayi Mensah",
        "Danfa",
        "Parts of Oyarifa",
        "Agyeman Katta",
        "A Line",
        "Rehoboth Estate",
        "Wisdom Square",
        "Buo Town",
        "Comet Estate",
        "Firestone",
        "Madina Zongo Junction",
        "Massalatsi",
        "RedCo Flats",
        "Jehovah Witness"
      ]
    }
  },
  {
    "id": "volta",
    "name": "Volta",
    "groups": {
      "A": [
        "Adidome Township",
        "Akyemfo",
        "Mali Anfoe",
        "Mepe Dagorme",
        "Adexor",
        "Battor Ghagbavunu",
        "Depe Knando Technical",
        "KPASEC",
        "Kpando Township",
        "Kudara",
        "part of Kpando Towns",
        "Ve-Golokwati",
        "Fume",
        "part of Nyagbo towns",
        "Logba Towns",
        "Part of Jasikan Township",
        "Apenkwa",
        "Bodada Towns",
        "Bowiri Towns",
        "Anfoeta Towns",
        "Dzolokpuita",
        "Amedzofe",
        "Dzologborgame",
        "Kpedze Towns",
        "Shiave",
        "Nyrve",
        "Matse",
        "Klefe Towns",
        "Ziavı Towns",
        "Microwave",
        "Alayı",
        "Soldiers Barracks",
        "Akpenamawu",
        "Da aba",
        "Police depot",
        "Akoefe",
        "Kpenoe",
        "Hodzoga",
        "Tanyigbe",
        "Part of Mafi Towns",
        "Aflas Township",
        "and Cross border Towns",
        "Kudje",
        "Worawora",
        "Tapa Amanya",
        "Kwamekrom",
        "part of Asickpe",
        "Kutime",
        "Adaklu Sofa",
        "Adaklu Waya. Kpoeta",
        "part of Hohoc",
        "Kpoeta and it's surroundings"
      ],
      "B": [
        "Oklahoma",
        "Lolobi Towns",
        "Likpe Towns",
        "Ayoma Towns",
        "Baglo Lakanti",
        "Kute Buem Tetema",
        "Akpafu Adorko",
        "Cross border Towns",
        "Agorpenu",
        "Sogakope township",
        "Dabala Town",
        "Adutor",
        "Tsavanya",
        "Tordzinu",
        "Klotekpo",
        "Gafatsikope",
        "Torve",
        "Logokukope",
        "Akatsi Township",
        "Live Towns",
        "Dzrakate",
        "Atidzive",
        "Abor",
        "Tadzewu",
        "Avalavi",
        "Fodome Towns",
        "part of Liati Towns",
        "Gbledi Towns",
        "Wli Towns",
        "part of Kpando Towns",
        "Akaa Towns",
        "Alavanyo Towns",
        "Nkonya Towns",
        "Gbi Akplamafu",
        "Hedzranawo",
        "Adina",
        "Kedzi",
        "Agavedzi",
        "Keta",
        "Kadjebi",
        "Asato",
        "Mount Sinai",
        "part of Jasikan",
        "Nkwanta",
        "part of Ho Township",
        "Part of UHAS main campus",
        "Adaklu Kodzobi",
        "Sokode Lokoe",
        "part of Sokode Gborgame",
        "Akrofu",
        "Abutia",
        "Rainbow",
        "Aflao Lowcost",
        "Agbokope",
        "Beach",
        "Avoeme",
        "Awakome",
        "Denu",
        "Lowcost",
        "Tsito Township and it's surroundings"
      ],
      "C": [
        "Tokor",
        "SPACO",
        "Kopeyia",
        "Dzodze",
        "Ave towns",
        "Nogokpo",
        "Agbozume",
        "Dzaglame",
        "Klikor",
        "Weta towns",
        "Taskcorner",
        "Ehi towns",
        "Afiadenyigba",
        "Nakyikope",
        "part of Akatsi Towns",
        "part of Ho Township",
        "Wumenu",
        "Agotime towns",
        "Kpetoe",
        "Agorhokpo",
        "Agorhome",
        "Sarakope",
        "Batume junction",
        "Akpokope",
        "Ziope towns",
        "Agonu towns",
        "Honugo",
        "Keklebesi",
        "Bedzame",
        "Part of Hohoe Township",
        "Waterworks",
        "part of Oklahoma",
        "Sovie",
        "Anfoega towns",
        "Aveme towns",
        "Vakpo",
        "Wusuta towns",
        "Tsrukpe towns",
        "Comboni",
        "Agordome",
        "Kepnu",
        "Agorta",
        "Svietula",
        "Angloga",
        "part of Keta",
        "Worawora",
        "Kabusu",
        "Apesukobi",
        "Ayeremu",
        "Katanga",
        "Asukokoo",
        "Dormabin",
        "Dambai",
        "Kpando Todzi",
        "Kpando Togorme",
        "Torkor",
        "Kpeve Township",
        "Kpalime Duga Toh Duga Tsibu",
        "South Dayi",
        "New Kaira",
        "Dzemeni",
        "Peki and it's surroundings"
      ]
    }
  },
  {
    "id": "ashanti",
    "name": "Ashanti",
    "groups": {
      "A": [
        "Parts of Eusu",
        "Kokobra",
        "Deduako",
        "Asamang",
        "Domeabra",
        "Aptomase",
        "Kokoben",
        "Donyina",
        "Appiadu",
        "Traboom",
        "Manso-Nkwanta",
        "Boko",
        "Twedie",
        "Fouse",
        "Antoukrom",
        "Seidi",
        "Clicks & Chicken",
        "Amankyea",
        "Essuowin",
        "Esaase Bontefofum",
        "Mpatuom",
        "Alhwerewa",
        "Absubo Tetekass",
        "Tetrem",
        "AkataneaseNweneso",
        "Odalım",
        "Atwire",
        "Abore",
        "Moscaso",
        "Kromom Cement",
        "Heman",
        "Amosaman",
        "Adunkwane",
        "Kokote",
        "Abira",
        "Namong",
        "Takyeman",
        "Denkyembouso",
        "Chwumasi",
        "Hill Top",
        "Part of Asouyebon",
        "Part of Tanoso",
        "Topreso",
        "Moshie Zonge",
        "Airport",
        "Part of Pankrono",
        "Part of Ahwia",
        "Kuma",
        "Apromoase",
        "Krapa Oldtown",
        "Krapa",
        "Part of Ejisu",
        "Bampenase",
        "Adubenso",
        "Adubensokese",
        "Swedru",
        "Adubensoben",
        "Aboabogya",
        "Bomfa",
        "Adumakasekese",
        "Sewaba",
        "Asabi",
        "Asokore Mampong",
        "Part of Paskoso",
        "Part of Affordable Housing Akokoamon",
        "Kyerekrom",
        "Ekyem",
        "Parkoso",
        "Aprede",
        "BRRI",
        "CRI",
        "Akorem",
        "Adukrom",
        "Dagomba line",
        "Oforikrom",
        "STC",
        "Onwe",
        "Ejisu Sec",
        "Tech",
        "Asounipon",
        "Donaso",
        "Achina",
        "Asumang",
        "Justice Hotel",
        "Amakom",
        "Stadum",
        "St. Paul Sch",
        "Awina Fanti Newtown",
        "Krofrom",
        "Ampahame",
        "Afrancho",
        "Kantenkyiren",
        "Kyerensa",
        "Hedase",
        "Adwampong",
        "Ahwiaa Town Cultural Centre",
        "Komfo Anokye SHS",
        "GBC",
        "Asafo Dadesnaba",
        "T.L",
        "AMASS",
        "Home tourch",
        "Baso Club",
        "Stadium",
        "Kontonpo",
        "Sepetinpome",
        "Asori Nkwanta",
        "Limex",
        "Dote",
        "Part of Duase",
        "Konongo",
        "Juuso",
        "Part of Low Cost",
        "Freetown",
        "Abosonmtwigya",
        "Yawkwet",
        "West Coast",
        "Asikafuoambantem",
        "Nkwanta",
        "Obogu",
        "Dulu",
        "Suabo",
        "Subinso",
        "Kumeaboe",
        "Takwae",
        "Yaw Asare",
        "Koiktum",
        "Dwendwenase",
        "Ataneata",
        "Atwedie",
        "Asankare",
        "Bompata",
        "Adanse",
        "Breku",
        "Asuobua",
        "Dampong",
        "Asokwa Oldtown",
        "Asokwa Pentecost",
        "Staduim Hotel",
        "Asokwa Sobolo",
        "Yaw Nkrumah",
        "Bonifa",
        "Asotwe",
        "Akyeakrom",
        "Forestry Sch",
        "Juuben",
        "Yabi",
        "Merewadwa",
        "Aburaso",
        "Kromouse",
        "Maase",
        "Adwenase",
        "Taabom",
        "Ababoga",
        "Essen",
        "Hyewhyew Akyeremade",
        "Chichibon",
        "Gyekye",
        "Dida",
        "Wawase",
        "Antobuave",
        "New Nsata",
        "Zongo",
        "Amangoase",
        "Kulumu",
        "Gausu",
        "Koffiekrom",
        "Sec Tech",
        "Forestry",
        "Nyameso",
        "Bediem",
        "Ofori Stadium",
        "Anyinam",
        "Anwonakrom",
        "Apitikuoko",
        "Apitiso No. 1 & 2",
        "Suhyenso",
        "Akaako",
        "Agycikrou",
        "Mile 9",
        "Twepease",
        "Mile 14",
        "Edwinase",
        "Atabrakoso",
        "Kwame Tanokrom",
        "Oseikrom",
        "Fenaso Nisvantu",
        "Abouyeikrom",
        "Abubuasin",
        "Menakrom",
        "CGyankobaah",
        "Nerebehi",
        "Nfensi",
        "Asafo",
        "Asafo Market",
        "Brigima",
        "Tarkwa Maakro",
        "Mpatasic",
        "Anomangye",
        "Part of Magazine",
        "Old & New Suame",
        "Purt of Abrepo",
        "Part of Bohyen",
        "Sawaba",
        "Denase",
        "Abenkyim",
        "Anwiankwanta",
        "Awhia",
        "Dominase",
        "Bhenase",
        "Ntinanko",
        "Pono",
        "Daa",
        "Apaaso",
        "Asanso Senfi",
        "Adjemesu",
        "Ofoase Kokoben",
        "Abano",
        "Obo",
        "Nyametiase",
        "Nkoainkwata",
        "Abretwen",
        "Kuwait",
        "Naachia",
        "Sawua and its environs",
        "Aprabon",
        "Mamponteng",
        "Agona",
        "Nsarta",
        "Kumawa",
        "Mampong Effiduse",
        "Ankaase",
        "Breman",
        "Part of Kronum",
        "Kronum Kwapra",
        "Sepaase",
        "Edwanfo",
        "Afari",
        "Nkawie",
        "Nerbehi",
        "Hiawu-Besease",
        "Ahuakaw-Makro",
        "Asikuma Town",
        "Mfuom",
        "Babianiha"
      ],
      "B": [
        "Moinssi Valley",
        "Akrofuom",
        "Jimiso",
        "Jimiso Kakraba",
        "Part of Bekwai Township",
        "Low Cost Est.",
        "Korkyerekrom",
        "Kwabetusu",
        "Anita Hotel",
        "Besease",
        "Breman Nkwantwima",
        "Part of Kronum",
        "Sasa",
        "Bouho",
        "Brofoyedru",
        "Ampabame",
        "Bodwesango",
        "Petransa",
        "Bomso",
        "Akyena",
        "Atrama",
        "Egyakon Bouhol&II",
        "Magazine",
        "Tafo New Road",
        "Tafo Nhyiaeso",
        "Tafo",
        "Adagya",
        "Esereso",
        "Jachie",
        "Pramso",
        "Abramkese",
        "Gh Water Office-Suame",
        "A-Lang",
        "Parts of Magazine",
        "Odeneho Kwadaso",
        "Agric Amanfrom",
        "Santasi Apire",
        "Old & New Suame",
        "Wawase",
        "Kwabrafoso",
        "Tutuka",
        "Aboagyekrom",
        "Boete",
        "Lowcost",
        "Brahabebume",
        "Atoplans",
        "Bossman",
        "Abuakaw-Makro",
        "Asonomaso",
        "Manhyia",
        "Koforidua",
        "Tabre",
        "Akwabuah",
        "Ntensere",
        "Mfensi",
        "Asakraka",
        "Part of Brofoyedru",
        "Deeper Life Kwamang",
        "Sanfo Aduam",
        "Adumasa",
        "Kokotro",
        "Essiase",
        "Wood village",
        "Bost",
        "Sokoban",
        "Asaago",
        "Odenchu Kwadaso",
        "Atasomanso",
        "Part of Santase",
        "Adiebeba",
        "Ahodwo",
        "Melcom",
        "Fankyenebra",
        "Odenehu Kwadaso",
        "Akrowa",
        "Kodie",
        "Apagya",
        "Akrofrom",
        "Patasi",
        "Aduman",
        "Aduamoah",
        "Denase",
        "Akom",
        "Nkwntakese",
        "Pampatia",
        "Sepaase",
        "Edwanfo",
        "Afari",
        "Nkawie",
        "Hiawu-Besease",
        "Gyankobaah",
        "Mpasatia",
        "Mankranso",
        "Kunso",
        "Boatenkrom",
        "Arokrom",
        "Goigoikrom",
        "Bonkwaso",
        "Pampaso",
        "Worakese",
        "Kwaso",
        "Essienimpong",
        "Agya Appiah",
        "Camp",
        "Deeper Life Camp",
        "Kotwi",
        "Nkransa",
        "Habitat",
        "Bekwame",
        "Kyekyewere",
        "Part of Kokoben",
        "Kokoben Ebenazer",
        "Atimatim Abrafi",
        "Part of Fawoade",
        "Asenua",
        "Part of Meduma",
        "Meduma Abass",
        "Kontomire",
        "Dwenenh",
        "Asempenaye",
        "Akaporiso",
        "Pomposo",
        "Asonkore",
        "Abusco",
        "Deawuoso Ayiase",
        "Part of Kropo",
        "Kuntenase",
        "Tafo Zongo",
        "Westley Girls Sch.",
        "Moro Market",
        "Menhyia",
        "Bronkra",
        "Part of Santasi",
        "Fankyrenbra",
        "Kaasi",
        "Ahinsan",
        "Coca Cola",
        "Ash Foam",
        "BLLC",
        "Appiah Menkah",
        "Abattoir",
        "Bomplex",
        "Opoku Transport",
        "Atia",
        "Kentinkrono",
        "Maxima Junction",
        "Ayegya Est.",
        "Part of Affordable Housing",
        "Ayegya Zongo",
        "Christian Village",
        "Santasi",
        "Anyinam",
        "Santasi Apire Amangoase",
        "Nsenie",
        "China Estate",
        "Bonfa",
        "Pepedan",
        "Esumaja",
        "Sebedie",
        "Kokofu",
        "Asankari",
        "Okyerekrom",
        "Wamasi",
        "Asanso",
        "SDA SHSch",
        "Zongo",
        "Amoafo",
        "Abodom",
        "Koniyaw",
        "Asokore",
        "Daimond hotel",
        "Yenyawoso",
        "CPC",
        "Dichemso",
        "Agona",
        "Kumawu",
        "Effiduase",
        "Nsuta",
        "Mampong",
        "Adoato",
        "Abrepokese",
        "Asubonteng",
        "Ohwum",
        "Amanfrom",
        "Adomanu",
        "Nyankerenease",
        "Bokankye",
        "Kokosu",
        "Town",
        "Part of Asendua",
        "Ahwiaa Newsite",
        "Ahwiaa Overseas",
        "Ahwiaa Adabraka",
        "Part of Medoma",
        "Buabenso",
        "Buaben",
        "Bekwai Bungalow",
        "Nampansa",
        "Amansie",
        "Asiebu",
        "Anwiam",
        "Part of Abirem",
        "Abirem Zongo",
        "Antoa",
        "Adesina",
        "Sisikro",
        "Bodoma",
        "Amponya",
        "Ataase",
        "Afoako",
        "Homase",
        "Bekrose",
        "Adubrem Penipa",
        "Asikuma"
      ],
      "C": [
        "Abakomade",
        "Part of Abuakwa",
        "Part of lanoso",
        "Paramount",
        "Formulation",
        "St. Elizabath",
        "Keesben Est. Ensonyameye",
        "Adwumam",
        "Adwumam Newsite",
        "Part of Fawoade",
        "Adagya",
        "Esereso",
        "Zoom Lion Factory",
        "Sesease",
        "KMA Residency",
        "Tigo main office",
        "Nhyayeso",
        "Asawase Market",
        "Zaabo Zongo",
        "Roman Girls",
        "Akawatia-Line",
        "Afia Kobi Market",
        "Cocoa Clinic",
        "A-life",
        "Part of Adum",
        "Railways Co.",
        "Bompata",
        "Fanti Newtown",
        "K Poly",
        "Part of Asafo",
        "Alabar",
        "Part of Ashtown",
        "KO",
        "Mbrom",
        "Yegola Hotel",
        "KTI",
        "Roman Hill",
        "Town hall",
        "SIC",
        "Zongo Police Station",
        "Part of Central Market",
        "Dakwadwum",
        "TUC",
        "Fankyenebra",
        "Teacher Nkwanta",
        "Kenkaese",
        "Dwansa",
        "Agogo",
        "Part of Low Cost",
        "Nyaboo",
        "Atonsu",
        "Petransa",
        "Kokoase Mines",
        "Bimma",
        "Obenemase",
        "Asonkore",
        "Alhaji Awal",
        "Kwabemnakwa",
        "Mampamhwe",
        "Nyamesomye",
        "Domeabra",
        "Tewobebi",
        "Nyamebekyere",
        "Nyakumasu",
        "Denase",
        "Asokwa",
        "Breman UGC",
        "Atimatim",
        "Atimatim Chairman",
        "Atimatim Bronkrom",
        "Atimatim Newsite",
        "Part of Pankrono",
        "Pankrono Abed",
        "Adukrom",
        "Dagomba line",
        "Oforikrom",
        "STC",
        "Maxima",
        "Bomso",
        "Susanso",
        "Susanekyre",
        "Awunaga",
        "Bantama",
        "Race Course",
        "Kajetei",
        "Cultural Centre",
        "Junction",
        "Aboabo",
        "Asawasi",
        "Hwiremoase",
        "Kyiraburoso",
        "Bronikrom",
        "New Edubiase",
        "Fumso",
        "Boadi",
        "Emina",
        "Ayeduase",
        "Apemso",
        "Deduako",
        "Anhiwiaso",
        "Praso",
        "Ataase Nkwanta",
        "Apagya",
        "Nsuta",
        "Boko",
        "Atobiase",
        "Nkranfo Nkwanta",
        "Atwereboma",
        "Ayanfuri Town",
        "Dominase",
        "Nkotimso",
        "Breku",
        "Pipiiso",
        "Atetem",
        "Atonsu S-line",
        "Gyinyase",
        "Kotei",
        "Charpatre",
        "Part of Ahinsan",
        "Ahinsan Est.",
        "Kwadaso",
        "Kwadaso Nsoum",
        "Asuoyeboa",
        "SSNIT Flat",
        "UCE-K'si",
        "Tanoso",
        "Pokukrom",
        "Apatrapa",
        "Bodwesango",
        "Piase",
        "Mim",
        "New Brodakwaw",
        "Beposo",
        "Kwadaso Estate",
        "Patase",
        "Police Depot",
        "Santase Roundabout",
        "Edwinase",
        "Asare Farms",
        "Nimo",
        "Kwadaso Ohwumase",
        "Part of Kwadaso",
        "Africa",
        "Bomfa",
        "Peminase",
        "Akronwe",
        "Esaase",
        "Wabiri",
        "Asiwa",
        "Appantubuom",
        "Kokoben",
        "Adeito",
        "Anyanso",
        "Fereboye",
        "Ofoase",
        "Boankra Port",
        "Hwereso",
        "Kubease",
        "Duapopom",
        "Koforidua",
        "Nobewam",
        "Konkori",
        "Kwanwoma",
        "Asaago",
        "Pakyi No. 1&2",
        "Int. Comm. Sch.",
        "Kwadaso Market",
        "CAC University",
        "Nyameani",
        "Kyekyebiase",
        "Pekyerekye",
        "Akutuase",
        "Wioso",
        "Dwereso",
        "Hwidiem",
        "Behwe",
        "Kenyase",
        "Kenyase Tewubabi",
        "Part of Abirem",
        "Bosore",
        "Akate Farms",
        "Nwamase",
        "Brofoyedu",
        "Garden City",
        "Duase",
        "Kronom",
        "Sepe",
        "Buokrom",
        "Airport Round-about",
        "Pankrono Est.",
        "Agya Appiah",
        "Buokrom Est.",
        "Buokrom South Africa",
        "Truba",
        "Abouhia",
        "Breman West",
        "KNUST",
        "Ayigya ECG Dist Office",
        "Banivillas Hostel",
        "Ghana Hostel",
        "Georgia Hostel",
        "Crystal Hostel",
        "Abusuakruwa",
        "Nwamasi",
        "Apire",
        "Henman",
        "Bebu",
        "Dako",
        "Adumasa",
        "Brofoyedru",
        "Ampabame No. 1&2",
        "Mpatase",
        "Trede",
        "Sabin Akrofrom",
        "Fumesua",
        "Kwamo",
        "Kwamo Highways",
        "Parts of Ejisu",
        "Bebre",
        "Kokobra",
        "Emuye",
        "Bedieso",
        "Mensakrom",
        "Gausu",
        "Kunka",
        "Nana Ponko",
        "New Dochiwaa",
        "Dadwene",
        "Kyekyewere Barrier",
        "Council Quarters",
        "Kwapia",
        "Akrokerri Training College",
        "Old Akrofuom",
        "Bobrase",
        "Akoowaso",
        "Hemang",
        "Bribiwormang"
      ]
    }
  },
  {
    "id": "tema",
    "name": "Tema",
    "groups": {
      "A": [
        "Lessure Hotel",
        "Nungua Zongo",
        "Kpeshie Police Headquarters",
        "Coco Beach",
        "Father's Hotel",
        "Mobole",
        "Afienya Taxi Station",
        "Toll Booth",
        "Emmanuel Estates",
        "Hot Oven",
        "Ablekuma",
        "CAC Imperial Peking",
        "China Mall",
        "Kaketo",
        "Okro Market",
        "Asensu Bar",
        "Apenyo",
        "Valco Flats",
        "Leonardo",
        "Adjetey Ansah",
        "Manheam SHS",
        "Naval Base",
        "Abonko",
        "Tema New Town Lorry Station",
        "Comm 19",
        "Buguin",
        "Awudu Issaka St Barkita",
        "Sethi Realty",
        "Abodakpi Farms",
        "MTN Junction",
        "Ghana Steel",
        "Kpone Dump Site",
        "Kpone Kokompe",
        "Ososhie",
        "Magna Terris",
        "Adom Estates",
        "Agbamami",
        "Avnash Residence",
        "Wilmar Residence",
        "BBC",
        "Comm. 2 Police Station",
        "TDC Shops",
        "Mirabake",
        "Kan Em TT Brothers",
        "Macharon Charlets",
        "BOST",
        "Frenchman",
        "Supreme Gas",
        "Ashaiman Timber Market",
        "Middle East",
        "Home and Away",
        "Methodist Junction",
        "ICGC",
        "Crystal Medical Center",
        "Datus",
        "Comm 7",
        "Jericho",
        "Roman Down",
        "Under Bridge Market",
        "State School for the Deaf",
        "Safisana",
        "Kanawu",
        "Adjei Kodjo Township",
        "BBF",
        "parts of Comm. 17",
        "Bake Shop",
        "Timber Market",
        "Resolve Hospital",
        "Bantsomaa Govemment School",
        "Kyereme Junction",
        "Marina Mall",
        "Baatsonma Total",
        "Sydal Farms",
        "Japan City",
        "Adjei Kodjo",
        "Global",
        "Teteman",
        "Emef Estates",
        "Lashibi",
        "Vodafon",
        "Celebrity Golf Club",
        "Sakumono Village Sakunone Estates",
        "High Tension Huena Vista Homes",
        "Fridays",
        "Njoy Hotel",
        "Agortor",
        "Shiloh",
        "Luta",
        "parts of Comm. 25",
        "Bediako",
        "High Tension",
        "Sackey Golf City Police Station",
        "Kent Estates",
        "HFC Estatex John Grey Estates",
        "ARS Church",
        "Mt Carmel",
        "Kakalika Plaza",
        "Standard Chatered Bank",
        "Shell Signboard",
        "Kpogas",
        "New Ningo",
        "Old Ningo",
        "Nungua Secondary School",
        "Channel 5",
        "Zimmerman Presbyterian Church",
        "Nungua Town Park",
        "Halian Boys Pub",
        "Later Day Saints",
        "Methodist junction",
        "Kpoo Keke",
        "Best Premier Hotel",
        "Nungua Nshornaa",
        "Fuel Trade",
        "Chase Petroleum",
        "WAPCo",
        "Aunty Kate",
        "Bankurman",
        "Naval Quarters",
        "Tema International School",
        "Don Bosco",
        "Bethlehem",
        "Sebrepor",
        "White Estates",
        "Goshen Ghetsile and its environs"
      ],
      "B": [
        "TIS Basic School",
        "Comm. 22",
        "Michell Camp",
        "Movelle",
        "European Market",
        "Comm 17",
        "Fafali",
        "HFC Estates",
        "Cambodia",
        "Santor",
        "Agbeshie Laryea",
        "Aunty Araba",
        "Nelplast",
        "Kubekro",
        "Level 400",
        "Katamanso",
        "Gbetsile",
        "Official Town",
        "Christian Village",
        "Clementina",
        "Ashaiman Circuit Courts",
        "Temascho",
        "Church of Brotherhood",
        "Charyass",
        "Railway Quarters",
        "Comm. 5",
        "Aponkye Clinic",
        "Irrigation",
        "Central University",
        "Ghanaman Soccer Academy",
        "Noble Estates",
        "Ghana Water(Prampram)",
        "Tsopoli",
        "Dawa",
        "Sege",
        "Kaseh",
        "Big Ada",
        "Ada Foah",
        "Totope",
        "Treasure Island",
        "Aqua Safari",
        "Lele Salt",
        "Palace Mall",
        "Lovely",
        "Kpone Barrier",
        "Frenchman",
        "Supreme Gas",
        "Ashaiman Timber Market",
        "Middle East",
        "Home and Away",
        "Motorway Total",
        "Alisa Hotel",
        "Square D",
        "VEHOCS",
        "Ltd",
        "Abbattoir",
        "Motorway Axle Station SRG Klagon",
        "NutriFoods",
        "Toyota Ghana Ltd",
        "Comm. 8",
        "B'S Maternity",
        "Akrade",
        "Senchi",
        "Atimpoku",
        "Akwamufie",
        "Juapong",
        "Volo",
        "Fintey",
        "Frankadua",
        "Nudu",
        "Kisifui",
        "African Fish Anum",
        "Boso",
        "Dodi Asantekrom",
        "Full Gospel Church",
        "Comm. 12",
        "Youth With a Mission",
        "FOS Aluminium",
        "Tanink",
        "Salvation Army",
        "Akuaba Estates",
        "Jehova Witness Assembly Hall",
        "parts of Coastal Estates",
        "Adotey Prampram Junction",
        "City Escape",
        "Potter's City",
        "Abia",
        "Prampram Township",
        "Kpoi Ete",
        "SSNIT Flats Comm. 5",
        "Valco Residence",
        "SOS Village",
        "parts of Comm. 10",
        "SOS",
        "Rama Down",
        "Able Academy School",
        "Timber Market",
        "Mavis Industries",
        "Comm. 25 Mall Polystar",
        "Maranatha Church",
        "LEKMA Polyclinic",
        "Adogonno",
        "Glow Lamp",
        "Frimpamaa Estates",
        "Abrantie",
        "Dan Adams",
        "First Choice",
        "Basket",
        "and its environs"
      ],
      "C": [
        "OLAM SHS",
        "Comm 4",
        "Joe Manu",
        "Lashibi Klagon",
        "Comm. 19 Annex",
        "EMEF Estates",
        "ECG Flats",
        "GNPC Flats",
        "IMaH",
        "Comm. 3",
        "Sites A & B",
        "BNI Flats",
        "MEDASS",
        "TOR Flats",
        "Adom FM",
        "Cocobod Flats",
        "VRA/GRIDCo Flats",
        "Womens' Hospital",
        "parts of Comm. 11",
        "Nuaso",
        "Agomanya",
        "St Martins' Hospital",
        "Lower Manya District Assebly Ofice",
        "Lebanon Zone 3",
        "Zenu",
        "Atadeka",
        "Legacy Girls",
        "Ghana Prisons",
        "Asutsuare",
        "Golden Exotics",
        "Volivo",
        "Shai Osudoku",
        "Commandos Military Training Camp",
        "Comm. 25",
        "Bulasu",
        "Ghana Flag",
        "Casilda Estates",
        "Afienya Zongo",
        "Dawhenya Township",
        "Abbey Kope",
        "Saglemi Housing",
        "Pharmanova",
        "Lakpleku",
        "Boiko",
        "Bundase Military Training Camp",
        "Afariwaa Junction",
        "Yellow Signboard",
        "Michell Camp Gate",
        "Kakasunaka #1",
        "Gbetsile Junction",
        "Gbetsile Lorry Station",
        "Soldier Line",
        "Comm. 11",
        "Ashaiman New Town",
        "Valco Flats Market",
        "parts of Jericho",
        "Odumse",
        "Christian International School",
        "Fiankonya",
        "parts of Mobole",
        "Otsebreku Okushibri",
        "Apollonia",
        "Jerusalem",
        "Katamanso",
        "Promised Land",
        "Data Center Elegant Homes",
        "P. S Global",
        "Devtraco Estates",
        "Kpone Affordable Housing",
        "Shang Hai",
        "Kpone Township",
        "PUMA Filling Station",
        "C&J Medical Centre",
        "Spintex Junction",
        "KFC",
        "Texpo",
        "Akorley Township",
        "Akorley Booster Station",
        "Adukrom Pumping Station",
        "Ahwiam",
        "Magotsonya",
        "Goi",
        "Kportitse Kope",
        "Songo Salt",
        "Lashibi Funeral Homes",
        "Vivian Farms",
        "Buena Vista Homes (Beach Drive)",
        "Posilipo",
        "Regional Maritime University",
        "Jomef",
        "Okro Garden",
        "Vodafone",
        "Comm 9 Market and its environs"
      ]
    }
  },
  {
    "id": "western-eastern-central",
    "name": "Western / Eastern / Central",
    "groups": {
      "A": [
        "Diabene",
        "Nkroful",
        "Kansawurodu",
        "Ntankoful",
        "Mt. Zion",
        "Race course",
        "Whundo",
        "Inchaban",
        "Nyankrom",
        "Shama junction",
        "Shama",
        "Aboudre",
        "Abuesi",
        "Discove",
        "Bustua",
        "Cape 3 pount",
        "Mpanyiasa",
        "Prestea township",
        "Mankesim",
        "Enyinam",
        "Pewodie",
        "Nyinawusu",
        "Diaso",
        "Juabo",
        "New Obuasi",
        "Ntom",
        "AgonaPort",
        "Ankwaso",
        "Henchena",
        "Asafo",
        "Kowf Hotel",
        "Starting Point",
        "Speesdigle",
        "ECG District Office",
        "Regional Hospital",
        "Anlo town",
        "Charlie Junction",
        "VHF",
        "Srodai",
        "Central Market",
        "Roman",
        "Amanase",
        "Kyekyewere",
        "Hudu",
        "Teacher Mantey",
        "Koans Estate",
        "Signboard",
        "Kusi",
        "Kade",
        "Okumaning",
        "Obo",
        "Obomeng",
        "Joe Oduro and its environs",
        "Osabene township",
        "Yan Botwe",
        "Kentenkeren",
        "Capital View Hotel",
        "Eastern Premier Hotel",
        "Adweso SSNIT Flat",
        "KTU",
        "Capital View Annex",
        "Universal School",
        "Munrovia",
        "Part of Okorase",
        "Domeabra",
        "Part of Bunso",
        "Nsutam",
        "Abompe",
        "Osino",
        "Saaman",
        "Anymam",
        "Kwabeng",
        "Mouso",
        "Akim Tafo Township",
        "CRIG",
        "Tontro",
        "Perchie",
        "Maase",
        "Awenare",
        "Abesim",
        "Part of Abepotia",
        "Wisrwisi",
        "Noyem",
        "Gyamase",
        "Pra River",
        "Kwame Dottoh",
        "Akouse",
        "Larbikrom",
        "Abirem",
        "Tafo Sabon Zongo",
        "Nobi",
        "Samresi",
        "Nsutapun",
        "Klo Agogo",
        "Boti Falls",
        "Huhunya",
        "Asesewa",
        "Akateng",
        "Nkurakan",
        "Valley Safari",
        "Ajumako township",
        "Enyan Denkyira Kwamakese",
        "Anomabo township",
        "Briwa",
        "Obokor",
        "Essueshia",
        "Eyisam",
        "Nakwa",
        "Ataabadze",
        "Twaa",
        "Atwaa",
        "Saltpond township",
        "Ankaful",
        "Saltpond hospital",
        "Anokyi",
        "Abonko",
        "Mfanstiman Girl",
        "Mankessun township",
        "Dominase Kyeakor",
        "Kwasi Ansa",
        "By- Pass",
        "Komaste",
        "Anomabo",
        "Ekrabadze",
        "Amoada",
        "Adamba Jukwa",
        "Effutu",
        "Heman",
        "Bremang Abrafo",
        "Assin Fosu township",
        "Abura Dunkwa",
        "Fante Nyakunase",
        "Yomoransa",
        "Asebu",
        "Edumfa",
        "Assin North and South",
        "Manso"
      ],
      "B": [
        "amreaboi",
        "Mumuni",
        "Atobrakrom",
        "Woman no good",
        "Yerase",
        "Akoon",
        "New Atuabo",
        "Cyanide",
        "Kwabedu",
        "Cape town",
        "Budo City",
        "Afere",
        "Bodi",
        "Aheinbenso",
        "Akontombra",
        "Essae",
        "Wiawso",
        "Bawdie",
        "Ankosia",
        "Adamanso",
        "Asikuma",
        "Wassa Akropong",
        "Saamaang",
        "Afransie",
        "Wassa Saa",
        "Wassa Japa",
        "Nanankor",
        "Nkonya",
        "Bogoso township",
        "Kokoase Adjeikrom",
        "Oppon Valley",
        "Awudua",
        "Samahu",
        "Himan township",
        "Brumasi",
        "Duamasi",
        "Kwemeniapa",
        "Ghana gas",
        "Afuke",
        "Dadieso",
        "Bonsu Nkwanta",
        "Asamankese township",
        "Yayo",
        "Part of Asamankese town",
        "Pinora Industries",
        "Bunso Lindador",
        "Forest Gate",
        "Adukrom",
        "Asikam",
        "Agyepongmaa",
        "Kibi",
        "Nkronso",
        "Potroase",
        "Pano",
        "Akooko",
        "Bepong",
        "Asakraka",
        "Kwahu Tafo",
        "Ankoma",
        "Kotoso",
        "Miaso",
        "Krofofrom",
        "Teacher Atta",
        "Akroso",
        "Agona Ninta",
        "Asouso",
        "Akim Koforidua",
        "Bantama",
        "Nkawkaw Novotex",
        "Amanfrom",
        "Saafi",
        "Awenade",
        "Apradang",
        "Fodua",
        "Besease",
        "Kwahu Praso",
        "Bunso Ayigbe town",
        "Ettukrom",
        "Osiem",
        "Bosuso",
        "Hemang",
        "Koradaso",
        "Begoro",
        "Obourho",
        "Ofoase",
        "Ayerebi",
        "Etwereso",
        "Gyadam",
        "Nkwateng",
        "Adweso",
        "Abogiri",
        "Two Streams",
        "Trom",
        "Medical Village",
        "Ghalloway",
        "Agavenya",
        "Korle Nkwanta",
        "Nkawkaw Trador",
        "Oframase",
        "Mpraeso Amanfrom",
        "Jejeti towns",
        "Kwahu Nsabah",
        "Asuboni Rails",
        "Akim Sekyere",
        "Enyiresi",
        "Roman",
        "Jamaica",
        "Zongo",
        "ECG District Office",
        "Kofigya",
        "Abenabo",
        "Akorabo",
        "Akote",
        "Jato",
        "Amanhyia",
        "ECG Main Office",
        "Ashanti Road",
        "Brofoyedur",
        "Idan Nstin",
        "Ekon",
        "Reg office",
        "Chapel Square",
        "Petrol",
        "Bakano",
        "Kotokruba Market",
        "Jubilee Sch",
        "Acquairium",
        "St",
        "Augustine",
        "Ola Estate",
        "UCC",
        "Industrial Estate",
        "Radio Central",
        "Sikafoambatem",
        "Siwidu compoud",
        "Adisadel Estate",
        "Industral Area",
        "West End",
        "Mfanstipim Flat",
        "4th Ridge",
        "Pedu Junction",
        "Pedu township",
        "Kakumdo",
        "Esuakyir",
        "1st",
        "2nd",
        "3rd Ridgs",
        "Nkanfoa",
        "Central Rgional Hospital",
        "Eguase",
        "Moree",
        "Akroma",
        "Ayensodo",
        "Kissi",
        "Komenda",
        "Agona",
        "Brase",
        "sekyere Hemang",
        "Bronyibima",
        "Sanka",
        "Attabadze town and Village",
        "Elmina town",
        "Bamtama",
        "Akwanda",
        "Brenu Akyem",
        "Peshie",
        "Elmina Shell",
        "Iture",
        "African Pot",
        "Amamuma",
        "Duakro",
        "Part of Ola township",
        "Elmina Zongo",
        "SNNIT Flat",
        "Atonkwan",
        "Amoada",
        "Nkontrodo",
        "Amisano",
        "Abie",
        "Ankaful Mental",
        "A kaful Prisons Manso",
        "Kushia",
        "Assin North & South",
        "Dompim",
        "Awuroso",
        "Assin Fosu town"
      ],
      "C": [
        "BU Junction",
        "Repso hills",
        "Fijai",
        "Adiembra",
        "Kweikuma",
        "New site",
        "New Amanful",
        "Takoradi Beach road",
        "Dupaul",
        "Apremdo",
        "Whindo",
        "Assakae",
        "Adientem",
        "Mpatado",
        "Sikafoabantem no.3",
        "Takoradi police reserve",
        "Collins Avenue",
        "Apowa",
        "Kejebir",
        "Mpohor",
        "Adum Banso",
        "Breman",
        "Kwabeng",
        "Agona",
        "Gyeduakese",
        "Moseasu",
        "Dominase Nkwanta",
        "Nkroful",
        "Telekubokazo",
        "Asasetre",
        "Bamiako",
        "Amanteng",
        "Manso",
        "Akontombra",
        "Juaboso",
        "Oda Quarters",
        "Akım Swedru SHS",
        "Asıkuma",
        "Amantopong",
        "Duakon",
        "Nkwatia",
        "Abetifi",
        "Pepease",
        "Hweehwee",
        "Sempoa",
        "Abene",
        "Ankaase",
        "Bula Spot",
        "Effiduase",
        "Asokore",
        "GHANASS",
        "Bohye",
        "Zongo",
        "Pipeline",
        "OBOSS",
        "Magazine",
        "Wawaso",
        "Suhum township",
        "Akwatia No.4",
        "Anweaso",
        "Atiankama Nkwanta",
        "Timber Market",
        "Achiase",
        "ECG District Office",
        "Part of Nkawkaw township",
        "Asoukaw",
        "Mepom",
        "Nyanoa",
        "Esaaso",
        "Nyankomase",
        "Osenase",
        "Kubriso",
        "Akanteng",
        "Part of Old Estate",
        "Paradise",
        "Residency",
        "Eredecs",
        "PURC",
        "Atekyem",
        "Nyamekrom",
        "Densu",
        "Part of Okorase",
        "Tei-Nkwanta",
        "Tinkong",
        "Konko",
        "Asasekorkor",
        "Adukrom Nyensi",
        "Adawso",
        "Mangoase",
        "Kwamoso",
        "Akim Oda Post Office",
        "Number 9",
        "Police Barracks",
        "Community 6",
        "Anerade",
        "Osorase",
        "Akosua Village",
        "Esukyir",
        "Ghaadze",
        "Okyereko",
        "Breku",
        "Senya",
        "Bonsuoko",
        "Gomoah Fetteh",
        "Akoti",
        "Ojobi",
        "Winger",
        "Kontokole",
        "Part of Mellennuim City",
        "Estate",
        "Adamukrom",
        "New Castle",
        "Menges",
        "Sandema",
        "Blue Kiosk",
        "Teacher Block Factory",
        "Anigye-Krom",
        "Opeikuma",
        "Asamoa",
        "Part of Colombo",
        "CP",
        "Lawyer",
        "Nyanyanu",
        "Yoo Mart",
        "Budunburam",
        "Nkwantenan",
        "Tipper Junction",
        "Roman",
        "Evalip",
        "Wallantu",
        "Gateway",
        "Newtown",
        "Kuwait",
        "Galilea Market",
        "TV3",
        "94 Washing Bay",
        "New Mrket",
        "American town",
        "Colomba",
        "Congo Villa",
        "Akweley",
        "Otta City",
        "Top town",
        "Nurses quarters",
        "Denchira",
        "Domeabra",
        "Kpormotey Ashalaja"
      ]
    }
  }
];

// Helper: Get current group(s) in outage right now
export function getCurrentOutageGroups() {
  const now = new Date();
  const dateStr = now.toISOString().split("T")[0];
  const timeStr = now.getHours().toString().padStart(2, "0") + ":" + now.getMinutes().toString().padStart(2, "0");

  const today = SCHEDULE_DATES.find(d => d.date === dateStr);
  if (!today) return [];

  return today.slots
    .filter(slot => {
      if (slot.end === "00:00") return timeStr >= slot.start;
      if (slot.start === "00:00") return timeStr < slot.end;
      return timeStr >= slot.start && timeStr < slot.end;
    })
    .map(slot => slot.group);
}

// Helper: Find which region+group an area belongs to
export function findArea(query) {
  const q = query.toLowerCase();
  for (const region of REGIONS_DATA) {
    for (const [group, areas] of Object.entries(region.groups)) {
      const match = areas.find(a => a.toLowerCase().includes(q));
      if (match) return { region, group, areaName: match };
    }
  }
  return null;
}

// Helper: Get next outage slot for a given group today
export function getNextSlot(group) {
  const now = new Date();
  const dateStr = now.toISOString().split("T")[0];
  const timeStr = now.getHours().toString().padStart(2, "0") + ":" + now.getMinutes().toString().padStart(2, "0");
  const today = SCHEDULE_DATES.find(d => d.date === dateStr);
  if (!today) return null;

  // Find next upcoming slot for this group today
  const upcoming = today.slots.find(slot => slot.group === group && slot.start > timeStr);
  if (upcoming) return { ...upcoming, date: today.date, day: today.day };

  // Check tomorrow
  const todayIndex = SCHEDULE_DATES.indexOf(today);
  if (todayIndex < SCHEDULE_DATES.length - 1) {
    const tomorrow = SCHEDULE_DATES[todayIndex + 1];
    const nextSlot = tomorrow.slots.find(s => s.group === group);
    if (nextSlot) return { ...nextSlot, date: tomorrow.date, day: tomorrow.day };
  }
  return null;
}
